"use client";

import Link from "next/link";
import { zodResolver } from "@hookform/resolvers/zod";
import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { CheckCircle, XCircle, RefreshCw, MessageSquare } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useSourcingCase, useSourcingCommand, useSourcingMembers, useSourcingSuppliers } from "@/hooks/queries";
import { sourcingQuoteSchema, type SourcingQuoteInput } from "@/lib/validations/sourcing";
import SourcingPurchaseOrderPanel from "./SourcingPurchaseOrderPanel";
import { formatMoney } from "@/lib/money";

const editableStages = ["draft", "sourcing", "changes_requested"];
const label = (value: string) => value.replaceAll("_", " ");
export default function SourcingCaseDetail({ caseId, basePath = "/sourcing" }: { caseId: string; basePath?: string }) {
  const [mounted, setMounted] = useState(false);
  useEffect(() => { setMounted(true); }, []);
  const { data: item, isLoading, error } = useSourcingCase(caseId); const command = useSourcingCommand(); const [dialog, setDialog] = useState<"assign" | "reason" | null>(null); const [reasonAction, setReasonAction] = useState("request_changes"); const [reason, setReason] = useState(""); const [assigneeId, setAssigneeId] = useState("");
  const { data: members = [] } = useSourcingMembers(item?.workspaceId || "", item?.capabilities?.canAssign); const { data: suppliers = [] } = useSourcingSuppliers(item?.workspaceId || "");
  const form = useForm<SourcingQuoteInput>({ resolver: zodResolver(sourcingQuoteSchema), defaultValues: { supplierName: "", unitPriceRmb: 0, samplePhotoUrls: [] } });
  const currentQuote = item?.quotes?.find((quote: any) => quote.status === "draft") || item?.quotes?.[0];
  useEffect(() => { if (currentQuote) form.reset({ supplierId: currentQuote.supplierId || null, supplierName: currentQuote.supplierName, unitPriceRmb: currentQuote.unitPriceRmb ?? 0, moq: currentQuote.moq, unitsPerCarton: currentQuote.unitsPerCarton, cartonDimensions: currentQuote.cartonDimensions, cartonWeightKg: currentQuote.cartonWeightKg, leadTimeDays: currentQuote.leadTimeDays, validUntil: currentQuote.validUntil ? new Date(currentQuote.validUntil).toISOString().slice(0, 16) : undefined, samplePhotoUrls: Array.isArray(currentQuote.samplePhotoUrls) ? currentQuote.samplePhotoUrls : [], remarks: currentQuote.notes }); }, [currentQuote, form]);
  if (!mounted || isLoading) return <main className="mx-auto max-w-5xl p-6"><div className="h-64 animate-pulse rounded-xl bg-muted" /></main>;
  if (error || !item) return <main className="p-6 text-destructive">Unable to load this sourcing case.</main>;
  const run = async (action: string, extra: Record<string, unknown> = {}) => { await command.mutateAsync({ id: item.id, version: item.version, action, ...extra }); setDialog(null); setReason(""); };
  const saveQuote = (action: "save_quote" | "submit_quote") => form.handleSubmit((quote) => run(action, { quote }))();
  const field = (name: keyof SourcingQuoteInput, labelText: string, type = "text") => <label className="grid gap-1 text-sm font-medium">{labelText}<Input type={type} {...form.register(name as any)} /></label>;
  return <main className="mx-auto max-w-5xl space-y-6 p-4 sm:p-6"><Link href={basePath} className="text-sm text-sky-600 hover:underline">Back to sourcing</Link><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">{item.title}</h1><p className="text-muted-foreground">{item.route === "other" ? "Other supplier route" : "Yiwu route"}</p></div><span className="rounded-full bg-muted px-3 py-1 text-sm capitalize">{label(item.stage)}</span></div>
    <Card><CardHeader><CardTitle>Request summary</CardTitle></CardHeader><CardContent className="grid gap-3 text-sm sm:grid-cols-2"><p><b>Size:</b> {item.size || "Not specified"}</p><p><b>Material:</b> {item.material || "Not specified"}</p><p><b>Variant:</b> {item.variant || "Not specified"}</p><p><b>Requested quantity:</b> {item.requestedQuantity ?? "Not specified"}</p><p><b>Target unit cost:</b> {item.targetUnitPriceMyr == null ? "Not specified" : formatMoney(item.targetUnitPriceMyr, "MYR")}</p><p><b>Assignee:</b> {item.assignee?.name || item.assignee?.email || "Unassigned"}</p><p><b>Reference:</b> {item.referenceUrl ? <a className="text-sky-600 underline" href={item.referenceUrl} target="_blank" rel="noopener noreferrer">Open link</a> : "None"}</p><p className="sm:col-span-2"><b>Specifications:</b> {item.specifications || item.description || "None"}</p><p className="sm:col-span-2"><b>Notes:</b> {item.notes || "None"}</p></CardContent></Card>
    <Card><CardHeader><CardTitle>Workflow</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-2">{item.capabilities.canAssign && <Button variant="outline" onClick={() => setDialog("assign")}>Assign sourcer</Button>}{item.capabilities.canDecide && item.stage === "quoted" && <><Button className="bg-green-600 text-white hover:bg-green-700" onClick={() => run("approve")}><CheckCircle className="h-4 w-4" />Approve quote</Button><Button className="bg-amber-500 text-white hover:bg-amber-600" onClick={() => { setReasonAction("request_changes"); setDialog("reason"); }}><MessageSquare className="h-4 w-4" />Request changes</Button><Button variant="destructive" onClick={() => { setReasonAction("reject"); setDialog("reason"); }}><XCircle className="h-4 w-4" />Reject</Button></>}{item.capabilities.canDecide && ["sourcing", "changes_requested"].includes(item.stage) && <Button variant="outline" onClick={() => { setReasonAction("cannot_source"); setDialog("reason"); }}>Cannot source</Button>}{item.capabilities.canOrder && <Button onClick={() => run("confirm_order")}>Create purchase order</Button>}{item.capabilities.canArchive && <Button variant="outline" onClick={() => run("archive")}>Archive</Button>}{item.stage === "archived" && item.capabilities.canAssign && <><Button variant="outline" onClick={() => run("revive")}><RefreshCw className="h-4 w-4" />Revive</Button><Button variant="outline" onClick={() => run("repeat")}>Repeat</Button></>}</CardContent></Card>
    {item.quotes?.length > 0 && !editableStages.includes(item.stage) && (() => { const submitted = item.quotes.find((q: any) => q.id === item.selectedQuoteId) || item.quotes.find((q: any) => q.status === "submitted") || item.quotes[0]; return submitted ? <Card><CardHeader><CardTitle>Supplier quote — revision {submitted.revision}<span className="ml-2 rounded-full bg-muted px-2 py-0.5 text-xs capitalize">{label(submitted.status)}</span></CardTitle></CardHeader><CardContent className="grid gap-3 text-sm sm:grid-cols-2"><p><b>Supplier:</b> {submitted.supplierName || "Not specified"}</p><p><b>CNY unit price:</b> {submitted.unitPriceRmb == null ? "Not specified" : formatMoney(submitted.unitPriceRmb, "CNY")}</p>{submitted.unitPriceMyr != null && <p><b>Approved MYR unit cost:</b> {formatMoney(submitted.unitPriceMyr, "MYR")}</p>}{submitted.fxRate && <p><b>Applied FX rate:</b> 1 CNY = {submitted.fxRate} MYR</p>}<p><b>MOQ:</b> {submitted.moq ?? "Not specified"}</p><p><b>Units/carton:</b> {submitted.unitsPerCarton ?? "Not specified"}</p><p><b>Carton dimensions:</b> {submitted.cartonDimensions || "Not specified"}</p><p><b>Carton weight (kg):</b> {submitted.cartonWeightKg ?? "Not specified"}</p><p><b>Lead time (days):</b> {submitted.leadTimeDays ?? "Not specified"}</p><p><b>Valid until:</b> {submitted.validUntil ? new Date(submitted.validUntil).toLocaleDateString() : "Not specified"}</p>{Array.isArray(submitted.samplePhotoUrls) && submitted.samplePhotoUrls.length > 0 && <p className="sm:col-span-2"><b>Sample photos:</b> {submitted.samplePhotoUrls.map((url: string, i: number) => <a key={i} className="text-sky-600 underline block" href={url} target="_blank" rel="noopener noreferrer">{url}</a>)}</p>}{submitted.notes && <p className="sm:col-span-2"><b>Remarks:</b> {submitted.notes}</p>}</CardContent></Card> : null; })()}
    {item.capabilities.canEditQuote && editableStages.includes(item.stage) && <Card><CardHeader><CardTitle>Supplier quote {currentQuote ? `revision ${currentQuote.revision}` : ""}</CardTitle></CardHeader><CardContent><form className="grid gap-4 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); saveQuote("save_quote"); }}><label className="grid gap-1 text-sm font-medium">Supplier<Select value={form.watch("supplierId") || "manual"} onValueChange={(value) => { const supplier = suppliers.find((entry: any) => entry.id === value); form.setValue("supplierId", value === "manual" ? null : value); if (supplier) form.setValue("supplierName", supplier.name); }}><SelectTrigger><SelectValue placeholder="Select supplier" /></SelectTrigger><SelectContent><SelectItem value="manual">Manual supplier name</SelectItem>{suppliers.map((supplier: any) => <SelectItem key={supplier.id} value={supplier.id}>{supplier.name}</SelectItem>)}</SelectContent></Select></label>{field("supplierName", "Supplier name")}{field("unitPriceRmb", "RMB unit price", "number")}{field("moq", "MOQ", "number")}{field("unitsPerCarton", "Units/carton", "number")}{field("cartonDimensions", "Carton dimensions")}{field("cartonWeightKg", "Carton weight (kg)", "number")}{field("leadTimeDays", "Lead time (days)", "number")}<label className="grid gap-1 text-sm font-medium">Valid until<Input type="datetime-local" {...form.register("validUntil")} /></label><label className="grid gap-1 text-sm font-medium sm:col-span-2">Sample photo URLs, one per line<Textarea {...form.register("samplePhotoUrls", { setValueAs: (value) => String(value).split("\n").map((url) => url.trim()).filter(Boolean) })} /></label><label className="grid gap-1 text-sm font-medium sm:col-span-2">Remarks<Textarea {...form.register("remarks")} /></label><div className="flex justify-end gap-2 sm:col-span-2"><Button type="submit" variant="outline" isLoading={command.isPending}>Save draft</Button><Button type="button" isLoading={command.isPending} onClick={() => saveQuote("submit_quote")}>Submit quote</Button></div></form></CardContent></Card>}
    <SourcingPurchaseOrderPanel orders={item.orders || []} basePath={basePath} /><Card><CardHeader><CardTitle>Timeline</CardTitle></CardHeader><CardContent className="space-y-3">{item.events?.map((event: any) => <div key={event.id} className="flex justify-between border-b pb-2 text-sm"><span className="capitalize">{label(event.type)}</span><span className="text-muted-foreground">{new Date(event.createdAt).toLocaleString()}</span></div>)}</CardContent></Card>
    <Dialog open={dialog === "assign"} onOpenChange={(open) => !open && setDialog(null)}><DialogContent><DialogHeader><DialogTitle>Assign sourcer</DialogTitle></DialogHeader><Select value={assigneeId} onValueChange={setAssigneeId}><SelectTrigger><SelectValue placeholder="Select member" /></SelectTrigger><SelectContent>{members.filter((member: any) => ["admin", "sourcer"].includes(member.role)).map((member: any) => <SelectItem key={member.id} value={member.id}>{member.name || member.email}</SelectItem>)}</SelectContent></Select><DialogFooter><Button disabled={!assigneeId} onClick={() => run("assign", { assigneeId })}>Assign</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={dialog === "reason"} onOpenChange={(open) => !open && setDialog(null)}><DialogContent><DialogHeader><DialogTitle>{label(reasonAction)}</DialogTitle></DialogHeader><Textarea value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Explain the decision" /><DialogFooter><Button disabled={!reason.trim()} onClick={() => run(reasonAction, { reason })}>Confirm</Button></DialogFooter></DialogContent></Dialog></main>;
}
