"use client";

import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { formatMoney } from "@/lib/money";
import type { MarketplacePlatform } from "@/lib/marketplace/analytics/types";
import { MarketplaceFilters } from "../analytics/MarketplaceFilters";
import { MarketplaceStatus } from "../analytics/MarketplaceStatus";
import { financialReportingCurrency, MarketplaceApiError, displayValue, fetchMarketplaceMetric, filtersFromSearchParams, marketplaceUrlQuery, type MarketplaceFiltersValue, type MarketplaceMetricResponse, type MarketplaceShopOption, validateMarketplaceFilters, withDefaultMarketplaceShop } from "../analytics/marketplaceAnalyticsUi";

export function MarketplaceProfitDashboard({ platform, title }: { platform: MarketplacePlatform; title: string }) {
  const router = useRouter(); const pathname = usePathname(); const searchParams = useSearchParams();
  const [draft, setDraft] = useState<MarketplaceFiltersValue>(() => filtersFromSearchParams(searchParams)); const [applied, setApplied] = useState<MarketplaceFiltersValue>(() => filtersFromSearchParams(searchParams)); const [filterError, setFilterError] = useState<string | null>(null);
  const shopsQuery = useQuery<{ shops: MarketplaceShopOption[] }>({ queryKey: ["marketplace-shops", platform], queryFn: async () => { const response = await fetch(`/api/marketplace/shops?platform=${platform}`); const body = await response.json().catch(() => null); if (!response.ok) throw new MarketplaceApiError(body?.error?.code ?? String(response.status), body?.error?.message ?? `Request failed with status ${response.status}`); return body; } });
  const shops = shopsQuery.data?.shops ?? [];
  const draftFilters = withDefaultMarketplaceShop(draft, shops);
  const appliedFilters = withDefaultMarketplaceShop(applied, shops);
  const analyticsEnabled = !shopsQuery.isLoading && shops.length > 0 && Boolean(appliedFilters.shopId || appliedFilters.allShops);
  const profitQuery = useQuery<MarketplaceMetricResponse>({ queryKey: ["marketplace-profit", "2026-analytics-v1", platform, appliedFilters], queryFn: ({ signal }) => fetchMarketplaceMetric(platform, "profit", appliedFilters, undefined, signal), enabled: analyticsEnabled, retry: 1 });
  const coverage = profitQuery.data?.financialCoverage; const profit = profitQuery.data?.data as Record<string, number | null> | undefined; const usable = coverage?.state === "ready";
  const productsQuery = useQuery({ queryKey: ["marketplace-profit-products", "2026-analytics-v1", platform, appliedFilters], queryFn: ({ signal }) => fetchMarketplaceMetric(platform, "products", appliedFilters, undefined, signal), enabled: usable, retry: 1 });
  const products = productsQuery.data?.data ?? [];
  const currency = financialReportingCurrency({ financialCoverage: coverage }); const money = (value: number | null | undefined) => displayValue(value, currency ? (number) => formatMoney(number, currency) : undefined);
  const apply = () => { const next = withDefaultMarketplaceShop(draft, shops); const error = validateMarketplaceFilters(next); if (error) return setFilterError(error); setFilterError(null); setApplied(next); const query = marketplaceUrlQuery(next); router.replace(`${pathname}${query ? `?${query}` : ""}`, { scroll: false }); };
  const exportCsv = () => { if (!usable) return; const rows: Array<Array<string | number>> = [["Metric", "Value"], ["Gross sales", money(profit?.grossSales)], ["Net sales", money(profit?.netSales)], ["Returned financial result", money(profit?.estimatedProfit)], [], ["Product", "SKU", "Quantity", "Gross sales", "Profit allocation"], ...products.map((product: { productName: string; sku: string | null; quantity: number | null; grossSales: number | null; estimatedProfit: number | null }) => [product.productName, product.sku ?? "", product.quantity ?? "Unavailable", money(product.grossSales), money(product.estimatedProfit)])]; const csv = rows.map((row) => row.map((value) => `"${String(value).replaceAll('"', '""')}"`).join(",")).join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); const link = document.createElement("a"); link.href = url; link.download = `${platform}-financial-analytics.csv`; link.click(); URL.revokeObjectURL(url); };
  const requestError = profitQuery.error as MarketplaceApiError | null;
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><h1 className="text-2xl font-bold">{title} Profit Tracking</h1><p className="text-muted-foreground">Marketplace financial analytics are gated by existing readiness. COGS, advertising, payroll, overhead, and unverified fields are excluded.</p></div><Button type="button" variant="outline" onClick={exportCsv} disabled={!usable}>Export financial CSV</Button></div>
    <MarketplaceFilters filters={draftFilters} shops={shops} shopsLoading={shopsQuery.isLoading} noShops={!shopsQuery.isLoading && shops.length === 0} error={filterError ?? (shopsQuery.error instanceof MarketplaceApiError ? `${shopsQuery.error.code}: ${shopsQuery.error.message}` : null)} onChange={setDraft} onApply={apply} />
    {profitQuery.isLoading && <p className="text-muted-foreground">Loading applied profit filters...</p>}{requestError && <p role="alert" className="text-destructive">{requestError.code}: {requestError.message}</p>}
    {!profitQuery.isLoading && !requestError && shops.length > 0 && <><MarketplaceStatus financialCoverage={coverage} capabilities={profitQuery.data?.capabilities} />{usable ? <><FinancialBreakdown profit={profit} money={money} coverage={coverage} /><ProductAllocation products={products} loading={productsQuery.isLoading} money={money} /></> : <Card><CardHeader><CardTitle>Marketplace financial analytics unavailable</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground">Financial breakdown, product allocation, and CSV export remain disabled because this selection is {coverage?.state ?? "unavailable"}. Missing capability or category: {coverage?.missingCostCategories?.join(", ") || coverage?.unavailableReasons?.join(", ") || "financial readiness is unavailable"}. Operational product and order insights are available in Analytics.</CardContent></Card>}</>}
  </div>;
}

function FinancialBreakdown({ profit, money, coverage }: { profit: Record<string, number | null> | undefined; money: (value: number | null | undefined) => string; coverage?: { calculationBasis?: string; financialCoveragePercent?: number | null; exclusions?: string[] } }) { const rows = [["Gross sales", profit?.grossSales], ["Seller discounts", profit?.sellerDiscounts], ["Refunds", profit?.refunds], ["Net sales", profit?.netSales], ["Buyer shipping credits", profit?.buyerShippingCredits], ["Marketplace fees", profit?.marketplaceFees], ["Payment fees", profit?.paymentFees], ["Seller shipping", profit?.sellerShipping], ["Return shipping", profit?.returnShipping], ["Returned financial result", profit?.estimatedProfit]]; return <Card><CardHeader><CardTitle>Marketplace financial analytics</CardTitle></CardHeader><CardContent><p className="mb-3 text-sm text-muted-foreground">Basis: {coverage?.calculationBasis ?? "unavailable"}; coverage: {coverage?.financialCoveragePercent ?? "Unavailable"}{coverage?.financialCoveragePercent === null || coverage?.financialCoveragePercent === undefined ? "" : "%"}. Excludes: {coverage?.exclusions?.join(", ") || "COGS, advertising, payroll, and overhead"}.</p><dl className="grid gap-2 text-sm sm:grid-cols-2">{rows.map(([label, value]) => <div key={label} className="flex justify-between gap-3"><dt>{label}</dt><dd>{money(value as number | null)}</dd></div>)}</dl></CardContent></Card>; }

function ProductAllocation({ products, loading, money }: { products: Array<{ productName: string; sku: string | null; quantity: number | null; grossSales: number | null; estimatedProfit: number | null }>; loading: boolean; money: (value: number | null | undefined) => string }) { return <Card><CardHeader><CardTitle>Product allocation</CardTitle></CardHeader><CardContent className="text-sm">{loading ? <p className="text-muted-foreground">Loading available allocation...</p> : products.length ? <div className="overflow-x-auto"><table className="w-full text-left"><thead><tr><th>Product</th><th>Quantity</th><th>Gross sales</th><th>Profit allocation</th></tr></thead><tbody>{products.map((product, index) => <tr key={`${product.sku ?? product.productName}-${index}`}><td>{product.productName}</td><td>{product.quantity ?? "Unavailable"}</td><td>{money(product.grossSales)}</td><td>{money(product.estimatedProfit)}</td></tr>)}</tbody></table></div> : <p className="text-muted-foreground">No available product allocation is available for this selection.</p>}</CardContent></Card>; }
