import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { FinancialCoverage, OperationalCoverage } from "./marketplaceAnalyticsUi";

export function MarketplaceStatus({ operationalCoverage, financialCoverage, capabilities }: { operationalCoverage?: OperationalCoverage; financialCoverage?: FinancialCoverage; capabilities?: Record<string, string> }) {
  const capabilityEntries = Object.entries(capabilities ?? {});
  const operational = operationalCoverage;
  const financial = financialCoverage;
  return <div className="grid gap-4 lg:grid-cols-2">
    <Card><CardHeader><CardTitle>{financial ? "Financial coverage" : "Operational coverage"}</CardTitle></CardHeader><CardContent className="space-y-1 text-sm text-muted-foreground">{financial ? <><p>State: {financial.state ?? "unavailable"}; basis: {financial.calculationBasis ?? "unavailable"}.</p><p>Certified orders: {financial.certifiedOrderCount ?? "Unavailable"} of {financial.rawOrderCount ?? "Unavailable"}; financial coverage: {financial.financialCoveragePercent ?? "Unavailable"}{financial.financialCoveragePercent === null || financial.financialCoveragePercent === undefined ? "" : "%"}.</p><p>Reporting currency: {financial.reportingCurrency ?? "Unavailable"}. Currencies: {financial.conversion?.sourceCurrencies?.join(", ") || "Unavailable"}; conversion is {financial.conversion?.applied ? "applied" : "not applied"}.</p></> : <><p>State: {operational?.state ?? "unavailable"}; availability: {operational?.availability ?? "unavailable"}.</p><p>Observed orders: {operational?.rawOrderCount ?? "Unavailable"}; items: {operational?.rawItemCount ?? "Unavailable"}.</p><p>Unknown status: {operational?.unknownStatusCount ?? "Unavailable"}; unknown quantity: {operational?.unknownQuantityCount ?? "Unavailable"}; unknown identity: {operational?.unknownIdentityCount ?? "Unavailable"}.</p><p>Source currencies: {operational?.sourceCurrencies?.join(", ") || "Unavailable"}.</p></>}</CardContent></Card>
    <Card><CardHeader><CardTitle>Capabilities</CardTitle></CardHeader><CardContent className="space-y-1 text-sm text-muted-foreground">{capabilityEntries.length ? capabilityEntries.map(([name, state]) => <p key={name}><span className="font-medium capitalize text-foreground">{name}</span>: {state}</p>) : <p>Capability checks have not completed.</p>}{financial?.missingCostCategories?.length ? <p>Missing categories: {financial.missingCostCategories.join(", ")}.</p> : null}{financial?.unavailableReasons?.length ? <p>Blocked by: {financial.unavailableReasons.join(", ")}.</p> : null}{operational?.reason ? <p>Blocked by: {operational.reason}</p> : null}</CardContent></Card>
  </div>;
}
